version: "2"
services:
  Calculator:
    build: ./CalculatorMS
    image: s222574652/calculator_ms
    env_file: ./CalculatorMS/.env
    command: node .
    ports:
      - "3001:4000"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    networks:
      front-tier:
        ipv4_address: $CALCULATOR_MS_IP
   
  Auth:
    build: ./AuthMS
    image: s222574652/auth_ms
    env_file: ./AuthMS/.env
    command: node .
    ports:
      - "3002:4000"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    networks:
      front-tier:
        ipv4_address: $AUTH_MS_IP


networks:
  front-tier:
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"
        